# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slamuda <- function(z, lamuda) {
    .Call('lllasso_slamuda', PACKAGE = 'lllasso', z, lamuda)
}

cacur <- function(y, x, belta, k, ro) {
    .Call('lllasso_cacur', PACKAGE = 'lllasso', y, x, belta, k, ro)
}

cacub <- function(lamuda, r, x, k, ro) {
    .Call('lllasso_cacub', PACKAGE = 'lllasso', lamuda, r, x, k, ro)
}

lasso2 <- function(y, x, lamuda) {
    .Call('lllasso_lasso2', PACKAGE = 'lllasso', y, x, lamuda)
}

